services:
  payload:
    # image: node:24-alpine
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: payload
    container_name: payload
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - pnpm_store:/home/node/.pnpm-store
      # - ~/.npmrc:/home/node/.npmrc:ro'
    environment:
      - NPM_CONFIG_USERCONFIG=/home/node/.npmrc
      - PNPM_STORE_DIR=/home/node/.pnpm-store
      - APP_CMD=${APP_CMD}
      # - NODE_OPTIONS="--max-old-space-size=4096"
    command: sh -c "pnpm ${APP_CMD}"
    working_dir: /app
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres
    command: postgres -c config_file=/var/lib/postgresql/postgresql.conf
    volumes:
      - pgdata:/var/lib/postgresql
      - ./postgres/postgresql.conf:/var/lib/postgresql/postgresql.conf:ro
      - ./postgres/pg_hba.conf:/var/lib/postgresql/pg_hba.conf:ro
    # ports:
    #   - '5432:5432'
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

volumes:
  pgdata:
  node_modules:
  pnpm_store:
