services:
  payload:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: payload
    container_name: payload
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - pnpm_store:/home/node/.pnpm-store
      - ~/.aws:/home/node/.aws
        # - ~/.npmrc:/home/node/.npmrc:ro'
    environment:
      - NODE_ENV=development
      - APP_CMD=${APP_CMD:-dev} # 默认为 dev
    command: sh -c "pnpm ${APP_CMD:-dev}"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres
    command: postgres -c config_file=/var/lib/postgresql/postgresql.conf
    volumes:
      - pgdata:/var/lib/postgresql
      - ./postgres/postgresql.conf:/var/lib/postgresql/postgresql.conf:ro
      - ./postgres/pg_hba.conf:/var/lib/postgresql/pg_hba.conf:ro
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

volumes:
  pgdata:
    external: true
    name: xc2f_pgdata
  pnpm_store:
