services:
  payload:
    image: node:24-alpine
    container_name: payload
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - pnpm_store:/home/node/.pnpm-store
      - ~/.npmrc:/home/node/.npmrc:ro'
    environment:
      - NPM_CONFIG_USERCONFIG=/home/node/.npmrc
      - PNPM_STORE_DIR=/home/node/.pnpm-store
    working_dir: /home/node/app/
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev"
    # command: sh -c "npm install -g pnpm && pnpm install && pnpm build && pnpm start"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

volumes:
  pgdata:
  node_modules:
  pnpm_store:
