name: 'ğŸš€ Build and Push Dev Image'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  DATABASE_URL: postgres://payload:payload@localhost:5432/payload
  NEXT_PUBLIC_SERVER_URL: ${{ vars.NEXT_PUBLIC_SERVER_URL }}

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    environment: production

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: payload
          POSTGRES_USER: payload
          POSTGRES_PASSWORD: payload
        options: >-
          --health-cmd="pg_isready -U payload"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Migrate database
        run: pnpm payload migrate

      - name: Build Next
        run: pnpm build

      - name: Prepare .dockerignore for Dev
        run: |
          # æŠŠ node_modules å’Œæ‰€æœ‰æºç æ‰“è¿›å»
          echo ".git" > .dockerignore
          echo ".next/cache" >> .dockerignore
          echo "node_modules/.cache" >> .dockerignore
          echo "==== Current .dockerignore ===="
          cat .dockerignore

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::022948663888:role/github-ci-role
          aws-region: us-east-1 # Public ECR å›ºå®šè¿™ä¸ª

      - name: Log in to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image (ARM64 only)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.prod
          push: true
          tags: |
            public.ecr.aws/umcai/xc2f/payload:dev-latest
          # å…³é”®ï¼šå¯ç”¨ GitHub Actions ç¼“å­˜ä¼˜åŒ–
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # æ˜ç¡®æŒ‡å®šå¹³å°ï¼ˆå› ä¸ºä½ è¿è¡Œåœ¨ arm ç¯å¢ƒï¼Œé»˜è®¤å°±æ˜¯ armï¼‰
          platforms: linux/arm64
